/* SCC v0.8.0: Database UI rebuild */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase();
const title=s=>clean(s).toLowerCase().replace(/(^|\s|[-'])\p{L}/gu,m=>m.toUpperCase());
function version(){document.title='SCC v0.8.0 · Database UI rebuild';document.querySelectorAll('.brand span').forEach(x=>x.textContent='v0.8.0');document.body.dataset.sccVersion='0.8.0'}
document.addEventListener('DOMContentLoaded',version); version();

const COUNTRY_CODE={
 'italy':'it','belgium':'be','spain':'es','brazil':'br','austria':'at','france':'fr','ireland':'ie','germany':'de','netherlands':'nl','portugal':'pt','united kingdom':'gb','great britain':'gb','uk':'gb','usa':'us','united states':'us','denmark':'dk','switzerland':'ch','australia':'au','poland':'pl','japan':'jp','china':'cn','south africa':'za','new zealand':'nz','canada':'ca','hong kong':'hk','romania':'ro','argentina':'ar','oman':'om','russia':'ru','belarus':'by','turkey':'tr','angola':'ao','indonesia':'id','qatar':'qa','united arab emirates':'ae','uae':'ae','india':'in','luxembourg':'lu','israel':'il','singapore':'sg','slovakia':'sk','sweden':'se','mexico':'mx','peru':'pe','ecuador':'ec','ukraine':'ua','thailand':'th','costa rica':'cr'
};
const DRIVER_COUNTRY_EXTRA={
 'jonny edgar':'United Kingdom','johnny edgar':'United Kingdom','tommaso mosca':'Italy','tomasso mosca':'Italy','yasser shahin':'Australia','petru umbrarescu':'Romania','alex aka':'Belgium','alessandro ghiretti':'Italy','aaron muss':'United Kingdom','adam smalley':'United Kingdom','ahmad al harthy':'Oman','alberto di folco':'Italy','aleksei nesov':'Russia','alessio picariello':'Belgium','alessio rovera':'Italy','alex fontana':'Switzerland','alexander bukhantsov':'United Kingdom','danial frost':'Singapore','enzo peugeot':'France','matej ryba':'Slovakia','lorenzo fluxa cross':'Spain','lorenzo fluxá cross':'Spain','louis iglesias':'France','mackenzie dodds':'United Kingdom','sebastian bach':'Denmark','lorenzo fecury':'Brazil','gonzalo gomez azza':'Spain','gonzalo gómez azza':'Spain','colin noble':'United Kingdom','jules caranta':'France','michael pitamber':'South Africa','narain karthikeyan':'India','mikkel pedersen':'Denmark','saif rashid':'United Arab Emirates','tom dillmann':'France','bijoy garg':'United States','jeremy clarke':'United States','max esterson':'United States','nikita johnson':'United States','dean macdonald':'United Kingdom','andrea caldarelli':'Italy','sandy mitchell':'United Kingdom','franck perera':'France','laurin heinrich':'Germany','harry king':'United Kingdom','klaus bachler':'Austria','klaus bachler':'Austria','klaus bachler':'Austria','klaus bachler':'Austria','klaus bachler':'Austria','morris schuring':'Netherlands','ryan hardwick':'United States','brendan iribe':'United States','frederik schandorff':'Denmark','ollie millroy':'United Kingdom','alessandro pier guidi':'Italy','jack aitken':'United Kingdom','ben hanley':'United Kingdom'
};
function canonicalCountry(c){if(!c)return'';const k=norm(c); const nice={usa:'United States',uk:'United Kingdom','great britain':'United Kingdom','united states of america':'United States'}; return nice[k] || title(c).replace(/\bUsa\b/g,'United States').replace(/\bUk\b/g,'United Kingdom');}
function lookupCountry(name,explicit){let c=canonicalCountry(explicit); if(c)return c; const key=norm(name); if(DRIVER_COUNTRY_EXTRA[key])return DRIVER_COUNTRY_EXTRA[key]; if(typeof window.lookupDriverCountry==='function'){c=canonicalCountry(window.lookupDriverCountry(name)); if(c)return c;} return '';}
function dbFlag(country){if(!country)return'<span class="db-no-flag">—</span>'; if(typeof window.flag==='function')return window.flag(country); const code=COUNTRY_CODE[norm(country)]||''; return code?`<span class="flag-emoji">${code.toUpperCase()}</span>`:'';}
function badge(cls){return typeof window.classBadge==='function'?window.classBadge(cls):`<span class="class-badge">${E(cls)}</span>`;}
function pct(n,d){return d?Math.round((n/d)*100):0;}
function races(){return (window.RACES||[]).filter(r=>Array.isArray(r.entries)&&r.entries.length);}
function entryKey(r,e){return `${r.id||r.event}|${e.no}|${e.team}|${e.class}`;}
function isFinished(e){const s=String(e.status||'FIN').toUpperCase(); return !['RET','DNF','DNS','DSQ','NC'].includes(s);}
function num(v){const n=parseInt(v,10); return Number.isFinite(n)?n:null;}
function winnerInClass(r,cls){let arr=(r.entries||[]).filter(e=>String(e.class)===String(cls)); arr.sort((a,b)=>(num(a.classPos)||999)-(num(b.classPos)||999)); return arr[0];}

const DOB_STORE_KEY='scc-driver-dob-v1';
const COUNTRY_STORE_KEY='scc-driver-country-v1';
function loadJson(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}}
function saveJson(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function calcAge(dob){if(!dob)return''; const d=new Date(dob); if(isNaN(d))return''; const now=new Date(); let a=now.getFullYear()-d.getFullYear(); const m=now.getMonth()-d.getMonth(); if(m<0||(m===0&&now.getDate()<d.getDate()))a--; return a>=0&&a<100?a:'';}
function dobMap(){return loadJson(DOB_STORE_KEY)}
function countryMap(){return loadJson(COUNTRY_STORE_KEY)}

function buildDrivers(){
 const by=new Map(), dob=dobMap(), cm=countryMap();
 races().forEach(r=>{
  (r.entries||[]).forEach(e=>{
   (e.drivers||[]).forEach(d=>{
    const name=clean(Array.isArray(d)?d[0]:d); if(!name)return; const key=norm(name);
    if(!by.has(key))by.set(key,{key,name,country:'',starts:0,finishes:0,overallWins:0,classWins:0,overallPodiums:0,classPodiums:0,ppOverall:0,ppClass:0,flOverall:0,flClass:0,teams:new Set(),constructors:new Set(),classes:new Set(),series:new Map(),records:[],seen:new Set()});
    const rec=by.get(key); let cc=cm[key]||lookupCountry(name,Array.isArray(d)?d[1]:''); if(cc)rec.country=cc;
    const ek=entryKey(r,e); if(!rec.seen.has(ek)){rec.seen.add(ek); rec.starts++; if(isFinished(e))rec.finishes++; rec.teams.add(e.team||''); rec.constructors.add(e.constructor||''); rec.classes.add(e.class||'');
     const op=num(e.overallPos); const cp=num(e.classPos); if(op===1)rec.overallWins++; if(cp===1)rec.classWins++; if(op&&op<=3)rec.overallPodiums++; if(cp&&cp<=3)rec.classPodiums++;
     const sid=r.series||'unknown'; if(!rec.series.has(sid))rec.series.set(sid,{id:sid,starts:0,finishes:0,overallWins:0,classWins:0,overallPodiums:0,classPodiums:0,ppOverall:0,ppClass:0,flOverall:0,flClass:0});
     const ss=rec.series.get(sid); ss.starts++; if(isFinished(e))ss.finishes++; if(op===1)ss.overallWins++; if(cp===1)ss.classWins++; if(op&&op<=3)ss.overallPodiums++; if(cp&&cp<=3)ss.classPodiums++;
     rec.records.push({race:r,entry:e,overallPos:e.overallPos||'',classPos:e.classPos||'',status:e.status||'FIN'});
    }
   });
  });
  const addPerf=(arr,kind)=>{(arr||[]).forEach(p=>{const key=norm(p.driver||''); if(!key||!by.has(key))return; const rec=by.get(key); const isOverall=norm(p.class)==='overall'; if(kind==='pp'){isOverall?rec.ppOverall++:rec.ppClass++;} else {isOverall?rec.flOverall++:rec.flClass++;} const sid=r.series||'unknown'; if(!rec.series.has(sid))rec.series.set(sid,{id:sid,starts:0,finishes:0,overallWins:0,classWins:0,overallPodiums:0,classPodiums:0,ppOverall:0,ppClass:0,flOverall:0,flClass:0}); const ss=rec.series.get(sid); if(kind==='pp'){isOverall?ss.ppOverall++:ss.ppClass++;} else {isOverall?ss.flOverall++:ss.flClass++;}})};
  addPerf(r.performance?.poles,'pp'); addPerf(r.performance?.fastestLaps,'fl');
 });
 return [...by.values()].map(d=>{d.dob=dob[d.key]||'';d.age=calcAge(d.dob);d.finishPct=pct(d.finishes,d.starts);d.winPct=pct(d.overallWins+d.classWins,d.starts);d.podiumPct=pct(d.overallPodiums+d.classPodiums,d.starts);d.ppPct=pct(d.ppOverall+d.ppClass,d.starts);d.flPct=pct(d.flOverall+d.flClass,d.starts);d.seriesStats=[...d.series.values()].sort((a,b)=>b.starts-a.starts);d.records.sort((a,b)=>String(b.race.date||'').localeCompare(String(a.race.date||'')));return d;}).sort((a,b)=>b.starts-a.starts||a.name.localeCompare(b.name));
}
function buildTeams(){const m=new Map(); races().forEach(r=>(r.entries||[]).forEach(e=>{const k=norm(e.team||'Unknown'); if(!m.has(k))m.set(k,{name:e.team||'Unknown',entries:0,races:new Set(),series:new Set(),constructors:new Set(),classes:new Set()}); const x=m.get(k); x.entries++; x.races.add(r.id||r.event); x.series.add(r.series); x.constructors.add(e.constructor); x.classes.add(e.class);})); return [...m.values()].sort((a,b)=>b.races.size-a.races.size||a.name.localeCompare(b.name));}
function buildConstructors(){const m=new Map(); races().forEach(r=>(r.entries||[]).forEach(e=>{const id=e.constructor||'unknown'; const k=norm(id); if(!m.has(k))m.set(k,{id,name:title(id),entries:0,races:new Set(),series:new Set(),models:new Set(),classes:new Set()}); const x=m.get(k); x.entries++; x.races.add(r.id||r.event); x.series.add(r.series); x.models.add(e.model); x.classes.add(e.class);})); return [...m.values()].sort((a,b)=>b.races.size-a.races.size||a.name.localeCompare(b.name));}
function buildCircuits(){const m=new Map(); races().forEach(r=>{const k=norm(r.circuit||r.event); if(!m.has(k))m.set(k,{name:r.circuit||r.event,country:r.country||'',races:0,series:new Set(),events:[],first:'',last:''}); const x=m.get(k); x.races++; x.series.add(r.series); x.events.push(r); if(!x.country)x.country=r.country||''; const y=String(r.date||'').slice(0,4); if(y){if(!x.first||y<x.first)x.first=y; if(!x.last||y>x.last)x.last=y;}}); return [...m.values()].sort((a,b)=>b.races-a.races||a.name.localeCompare(b.name));}
function counts(){return {drivers:buildDrivers().length,teams:buildTeams().length,constructors:buildConstructors().length,circuits:buildCircuits().length,races:races().length};}
function diag(){const c=counts();return `<div class="db8-diagnostics"><b>Database</b><span>${c.races} races</span><span>${c.drivers} drivers</span><span>${c.teams} teams</span><span>${c.constructors} constructors</span><span>${c.circuits} circuits</span><button id="rebuildDbBtn" class="mini-button">↻ Rebuild</button></div>`}
function seriesName(id){return (window.SERIES&&SERIES[id]?.short)||id||'—'}
function carLogo(id){return typeof window.logo==='function'?window.logo('constructor',id,'db8-mini-logo'):'';}
function saveSelected(d){const dob=dobMap(), cm=countryMap(); const cd=$('dbDriverCountry')?.value||''; const bd=$('dbDriverDob')?.value||''; if(cd)cm[d.key]=canonicalCountry(cd); else delete cm[d.key]; if(bd)dob[d.key]=bd; else delete dob[d.key]; saveJson(COUNTRY_STORE_KEY,cm); saveJson(DOB_STORE_KEY,dob); renderDrivers8(d.key);}
function statTile(label,overall,classv,rate){return `<div class="db8-stat"><span>${label}</span><div><b>${overall}</b><em>overall</em><b>${classv}</b><em>class</em></div>${rate!=null?`<small>${rate}%</small>`:''}</div>`;}
function driverDetail(d){if(!d)return `<aside class="db8-detail"><div class="empty-state">Select a driver.</div></aside>`;return `<aside class="db8-detail"><section class="db8-profile"><div class="db8-avatar">${E(d.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase())}</div><div><h2>${E(d.name)} ${dbFlag(d.country)}</h2><p>${E(d.country||'unknown')} · ${[...d.classes].filter(Boolean).map(x=>badge(x)).join(' ')}</p><div class="db8-edit"><label>Nationality <input id="dbDriverCountry" value="${E(d.country||'')}"></label><label>Born <input id="dbDriverDob" type="date" value="${E(d.dob||'')}"></label><button id="dbSaveDriver" class="mini-button">Save</button><span>${d.age?`age ${d.age}`:'age unknown'}</span></div></div></section><section class="db8-stats"><div class="db8-stat starts"><span>Starts</span><strong>${d.starts}</strong><small>${d.finishes} classified · ${d.finishPct}%</small></div>${statTile('Wins',d.overallWins,d.classWins,d.winPct)}${statTile('Podiums',d.overallPodiums,d.classPodiums,d.podiumPct)}${statTile('Pole positions',d.ppOverall,d.ppClass,d.ppPct)}${statTile('Fastest laps',d.flOverall,d.flClass,d.flPct)}<div class="db8-stat"><span>Best class</span><strong>${d.classWins?'C1':'—'}</strong><small>${[...d.classes].filter(Boolean).join(', ')}</small></div></section><h3>By series</h3><div class="db8-series-grid">${d.seriesStats.map(s=>`<div><strong>${E(seriesName(s.id))}</strong><span>${s.starts} starts · ${s.finishes} fin.</span><span>W ${s.overallWins}/${s.classWins} · P ${s.overallPodiums}/${s.classPodiums} · PP ${s.ppOverall}/${s.ppClass} · FL ${s.flOverall}/${s.flClass}</span></div>`).join('')}</div><h3>Race history</h3><div class="db8-history"><div class="head"><span>Date</span><span>Series</span><span>Race</span><span>Team</span><span>Car</span><span>Class</span><span>Overall</span><span>Class</span></div>${d.records.map(r=>`<div><span>${E(r.race.date||'')}</span><span>${E(seriesName(r.race.series))}</span><span>${E(r.race.event||r.race.name||'')}</span><span>${E(r.entry.team||'')}</span><span>${carLogo(r.entry.constructor)} ${E(r.entry.model||'')}</span><span>${badge(r.entry.class)}</span><span>${r.overallPos?`P${E(r.overallPos)}`:'—'}</span><span>${r.classPos?`C${E(r.classPos)}`:'—'}</span></div>`).join('')}</div></aside>`}
function filteredDrivers(){let a=buildDrivers(); const f=window.state.driverFilters8||(window.state.driverFilters8={}); const q=norm(f.q), c=norm(f.country); if(q)a=a.filter(d=>norm(d.name+' '+[...d.teams].join(' ')).includes(q)); if(c)a=a.filter(d=>norm(d.country).includes(c)); if(f.series&&f.series!=='all')a=a.filter(d=>d.series.has(f.series)); [['ageMin','age'],['startsMin','starts'],['winsMin','classWins'],['podiumsMin','classPodiums'],['ppMin','ppClass'],['flMin','flClass'],['finishMin','finishPct']].forEach(([k,prop])=>{if(f[k]!==''&&f[k]!=null){const v=+f[k]; if(!isNaN(v))a=a.filter(d=>(+d[prop]||0)>=v)}}); const sort=window.state.driverSort8||{key:'starts',dir:'desc'}; a.sort((x,y)=>{let A=x[sort.key],B=y[sort.key]; if(sort.key==='name'||sort.key==='country'){A=String(A||'');B=String(B||'');return sort.dir==='asc'?A.localeCompare(B):B.localeCompare(A)} A=+A||0;B=+B||0; return sort.dir==='asc'?A-B:B-A}); return a;}
function sortBtn(label,key){const s=window.state.driverSort8||{};return `<button class="db8-sort ${s.key===key?'active':''}" data-db8-sort="${key}">${label}${s.key===key?(s.dir==='asc'?' ↑':' ↓'):''}</button>`;}
function renderDrivers8(selectedKey){const f=window.state.driverFilters8||(window.state.driverFilters8={q:'',country:'',series:'all',ageMin:'',startsMin:'',winsMin:'',podiumsMin:'',ppMin:'',flMin:'',finishMin:''}); const all=filteredDrivers(); const selected=all.find(d=>d.key===selectedKey)||all.find(d=>d.key===window.state.selectedDriver8)||all[0]; if(selected)window.state.selectedDriver8=selected.key; const series=['all',...[...new Set(races().map(r=>r.series).filter(Boolean))]]; const rows=all.map((d,i)=>`<div class="db8-driver-row ${selected&&selected.key===d.key?'selected':''}" data-db8-driver="${E(d.key)}"><span>${i+1}</span><strong>${E(d.name)}</strong><span>${dbFlag(d.country)} ${E(d.country||'')}</span><span>${d.age||'—'}</span><span>${d.starts}</span><span>${d.overallWins}/${d.classWins}</span><span>${d.overallPodiums}/${d.classPodiums}</span><span>${d.ppOverall}/${d.ppClass}</span><span>${d.flOverall}/${d.flClass}</span><span>${d.finishPct}%</span></div>`).join(''); $('dataManager').innerHTML=`${diag()}<div class="db8-layout"><section class="db8-list"><div class="db8-head"><h3>Drivers</h3><span>${all.length} / ${buildDrivers().length}</span></div><div class="db8-filters"><input id="db8Search" placeholder="Name or team…" value="${E(f.q||'')}"><input id="db8Country" placeholder="Nationality…" value="${E(f.country||'')}"><select id="db8Series">${series.map(id=>`<option value="${E(id)}" ${(f.series||'all')===id?'selected':''}>${id==='all'?'All series':E(seriesName(id))}</option>`).join('')}</select><input id="db8AgeMin" type="number" placeholder="Age ≥" value="${E(f.ageMin||'')}"><input id="db8StartsMin" type="number" placeholder="Starts ≥" value="${E(f.startsMin||'')}"><input id="db8WinsMin" type="number" placeholder="Wins ≥" value="${E(f.winsMin||'')}"><input id="db8PodiumsMin" type="number" placeholder="Podiums ≥" value="${E(f.podiumsMin||'')}"><input id="db8PpMin" type="number" placeholder="PP ≥" value="${E(f.ppMin||'')}"><input id="db8FlMin" type="number" placeholder="FL ≥" value="${E(f.flMin||'')}"><input id="db8FinishMin" type="number" placeholder="Finish % ≥" value="${E(f.finishMin||'')}"><button id="db8Clear" class="mini-button">Clear</button></div><div class="db8-driver-row db8-table-head"><span>#</span>${sortBtn('Name','name')}${sortBtn('Nationality','country')}${sortBtn('Age','age')}${sortBtn('Starts','starts')}${sortBtn('Wins O/C','classWins')}${sortBtn('Pod O/C','classPodiums')}${sortBtn('PP O/C','ppClass')}${sortBtn('FL O/C','flClass')}${sortBtn('Finish %','finishPct')}</div><div class="db8-rows">${rows||'<div class="empty-state">No drivers match current filters.</div>'}</div></section>${driverDetail(selected)}</div>`; bindDb8();}
function bindDb8(){const ids=[['db8Search','q'],['db8Country','country'],['db8Series','series'],['db8AgeMin','ageMin'],['db8StartsMin','startsMin'],['db8WinsMin','winsMin'],['db8PodiumsMin','podiumsMin'],['db8PpMin','ppMin'],['db8FlMin','flMin'],['db8FinishMin','finishMin']]; ids.forEach(([id,k])=>{const el=$(id); if(!el)return; const ev=()=>{const pos=('selectionStart'in el)?el.selectionStart:null; window.state.driverFilters8=window.state.driverFilters8||{}; window.state.driverFilters8[k]=el.value; renderDrivers8(); const ne=$(id); if(ne){ne.focus(); if(pos!=null)try{ne.setSelectionRange(pos,pos)}catch{}}}; el.oninput=ev; el.onchange=ev;}); document.querySelectorAll('[data-db8-driver]').forEach(r=>r.onclick=()=>renderDrivers8(r.dataset.db8Driver)); document.querySelectorAll('[data-db8-sort]').forEach(b=>b.onclick=()=>{const key=b.dataset.db8Sort; const cur=window.state.driverSort8||{}; window.state.driverSort8={key,dir:cur.key===key&&cur.dir==='desc'?'asc':'desc'}; renderDrivers8();}); const cl=$('db8Clear'); if(cl)cl.onclick=()=>{window.state.driverFilters8={q:'',country:'',series:'all',ageMin:'',startsMin:'',winsMin:'',podiumsMin:'',ppMin:'',flMin:'',finishMin:''}; renderDrivers8();}; const save=$('dbSaveDriver'); if(save){const d=buildDrivers().find(x=>x.key===window.state.selectedDriver8); save.onclick=()=>d&&saveSelected(d);} const rb=$('rebuildDbBtn'); if(rb)rb.onclick=()=>renderDataManager();}
function grid(items,kind){return `${diag()}<section class="db8-card-section"><div class="db8-head"><h3>${kind}</h3><span>${items.length}</span></div><div class="db8-card-grid">${items.map(x=>{if(kind==='Circuits')return`<div class="db8-card"><h3>${dbFlag(x.country)} ${E(x.name)}</h3><p>${E(x.country||'')}</p><b>${x.races} races</b><span>${[...x.series].map(seriesName).join(' · ')}</span><small>${x.first&&x.last?`${x.first}–${x.last}`:''}</small></div>`; if(kind==='Constructors')return`<div class="db8-card constructor"><div>${carLogo(x.id)}</div><h3>${E(x.name)}</h3><p>${x.races.size} races · ${x.entries} entries</p><span>${[...x.series].map(seriesName).join(' · ')}</span><small>${[...x.models].filter(Boolean).slice(0,5).map(E).join(', ')}</small></div>`; return`<div class="db8-card"><h3>${E(x.name)}</h3><p>${x.races.size} races · ${x.entries} entries</p><span>${[...x.series].map(seriesName).join(' · ')}</span><small>${[...x.constructors].filter(Boolean).map(title).join(', ')}</small></div>`;}).join('')}</div></section>`;}
function showTab(tab){window.state.dataTab=tab||'drivers'; document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active')); const sec=$('tab-data'); if(sec)sec.classList.add('active'); document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='data')); document.querySelectorAll('.database-nav button,.data-tab').forEach(b=>b.classList.toggle('active',(b.dataset.dbTab||b.dataset.dataTab)===window.state.dataTab)); window.renderDataManager();}
window.renderDataManager=function(){if(!$('dataManager'))return; const tab=window.state.dataTab||'drivers'; document.querySelectorAll('.database-nav button,.data-tab').forEach(b=>b.classList.toggle('active',(b.dataset.dbTab||b.dataset.dataTab)===tab)); if(tab==='teams'){$('dataManager').innerHTML=grid(buildTeams(),'Teams'); return;} if(tab==='constructors'){$('dataManager').innerHTML=grid(buildConstructors(),'Constructors'); return;} if(tab==='circuits'){$('dataManager').innerHTML=grid(buildCircuits(),'Circuits'); return;} renderDrivers8();};
// disabled old DB click listener; v0.8.4 owns DB routing
})();
