/* SCC v0.8.2.1: hard database UI repair + WEC PDF parser cleanup */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase();
function titleName(s){return clean(s).toLowerCase().replace(/(^|\s|[-'])\p{L}/gu,m=>m.toUpperCase()).replace(/\bAf\b/g,'AF').replace(/\bTf\b/g,'TF').replace(/\bBmw\b/g,'BMW').replace(/\bWrt\b/g,'WRT');}
function svgFlag(country){ if(window.flag) return window.flag(country)||''; return country?`<span class="flag-mini">${esc(country).slice(0,2).toUpperCase()}</span>`:''; }
const CTRY={
 'antonio fuoco':'Italy','miguel molina':'Spain','nicklas nielsen':'Denmark','robin frijns':'Netherlands','rene rast':'Germany','sheldon van der linde':'South Africa','kevin magnussen':'Denmark','raffaele marciello':'Switzerland','dries vanthoor':'Belgium','harry tincknell':'United Kingdom','tom gamble':'United Kingdom','mike conway':'United Kingdom','kamui kobayashi':'Japan','nyck de vries':'Netherlands','yifei ye':'China','y ye':'China','robert kubica':'Poland','phil hanson':'United Kingdom','paul di resta':'United Kingdom','stoffel vandoorne':'Belgium','nick cassidy':'New Zealand','andre lotterer':'Germany','andré lotterer':'Germany','luis felipe derani':'Brazil','mathys jaubert':'France','will stevens':'United Kingdom','norman nato':'France','louis deletraz':'Switzerland','sebastien buemi':'Switzerland','brendon hartley':'New Zealand','ryo hirakawa':'Japan','frederic makowiecki':'France','frédéric makowiecki':'France','jules gounon':'France','victor martins':'France','antonio felix da costa':'Portugal','antónio félix da costa':'Portugal','charles milesi':'France','ferdinand habsburg':'Austria','matthieu jaminet':'France','paul loup chatin':'France','daniel juncadella':'Spain','alessio rovera':'Italy','francois heriau':'France','françois hériau':'France','simon mann':'United Kingdom','hadrien david':'France','petru umbrarescu':'Romania','clemens schmid':'Austria','jose maria lopez':'Argentina','josé maría lópez':'Argentina','ben keating':'United States','jonny edgar':'United Kingdom','nicky catsburg':'Netherlands','darren leung':'United Kingdom','sean gelael':'Indonesia','augusto farfus':'Brazil','davide rigon':'Italy','tommaso mosca':'Italy','tomasso mosca':'Italy'
};
function countryFor(n){return CTRY[norm(n)] || (window.DRIVER_COUNTRIES&&(window.DRIVER_COUNTRIES[norm(n)]||window.DRIVER_COUNTRIES[clean(n)])) || '';}
function allRaces(){let r=Array.isArray(window.RACES)?window.RACES.slice():[]; try{const s=JSON.parse(localStorage.getItem('scc_saved_races_v081')||'[]'); if(Array.isArray(s)) r=r.concat(s);}catch{} const m=new Map(); r.forEach(x=>{if(x&&x.id&&!m.has(x.id))m.set(x.id,x)}); return [...m.values()];}
function driversOf(e){return (e.drivers||[]).map(d=>Array.isArray(d)?d[0]:d).map(clean).filter(Boolean);}
function dCountry(e,i,name){const d=(e.drivers||[])[i]; return (Array.isArray(d)&&d[1]) || countryFor(name) || '';}
function isFin(e){return !/RET|DNF|DNS|DSQ|NC|NOT/i.test(String(e.status||'FIN'));}
function cpos(e){return +(e.classPos||e.__classPos||e.cpos||0)||0}
function opos(e){return +(e.pos||e.overallPos||0)||0}
function ensureClassPos(r){const by={}; (r.entries||[]).forEach(e=>{const cls=e.class||'ALL'; by[cls]??=[]; by[cls].push(e)}); Object.values(by).forEach(arr=>arr.sort((a,b)=>opos(a)-opos(b)).forEach((e,i)=>{if(!e.classPos)e.classPos=i+1;}));}
function buildDrivers(){const by=new Map(); const dobs=JSON.parse(localStorage.getItem('scc_driver_dobs_v082')||'{}'); const edits=JSON.parse(localStorage.getItem('scc_driver_countries_v082')||'{}');
 allRaces().forEach(r=>{ensureClassPos(r); (r.entries||[]).forEach(e=>driversOf(e).forEach((name,i)=>{const k=norm(name); if(!k)return; if(!by.has(k))by.set(k,{k,name,country:'',dob:dobs[k]||'',starts:0,finishes:0,ow:0,cw:0,op:0,cp:0,ppO:0,ppC:0,flO:0,flC:0,series:{},hist:[],seen:new Set()}); const d=by.get(k); d.country=edits[k]||d.country||dCountry(e,i,name); const unique=`${r.id}|${e.no}|${e.class}`; if(d.seen.has(unique))return; d.seen.add(unique); d.starts++; if(isFin(e))d.finishes++; if(opos(e)===1)d.ow++; if(cpos(e)===1)d.cw++; if(opos(e)>0&&opos(e)<=3)d.op++; if(cpos(e)>0&&cpos(e)<=3)d.cp++; const sid=r.series||'unknown'; d.series[sid]??={starts:0,finishes:0,ow:0,cw:0,op:0,cp:0,ppO:0,ppC:0,flO:0,flC:0}; const s=d.series[sid]; s.starts++; if(isFin(e))s.finishes++; if(opos(e)===1)s.ow++; if(cpos(e)===1)s.cw++; if(opos(e)>0&&opos(e)<=3)s.op++; if(cpos(e)>0&&cpos(e)<=3)s.cp++; d.hist.push({race:r,e}); }));
  function perf(arr,kind){(arr||[]).forEach(p=>{const k=norm(p.driver); const d=by.get(k); if(!d)return; const overall=/^overall$/i.test(p.class||''); const sid=r.series||'unknown'; d.series[sid]??={starts:0,finishes:0,ow:0,cw:0,op:0,cp:0,ppO:0,ppC:0,flO:0,flC:0}; const prop=kind+(overall?'O':'C'); d[prop]++; d.series[sid][prop]++;});}
  perf(r.performance&&r.performance.poles,'pp'); perf(r.performance&&r.performance.fastestLaps,'fl'); });
 return [...by.values()].sort((a,b)=>b.starts-a.starts||a.name.localeCompare(b.name));}
function seriesName(id){return (window.SERIES&&SERIES[id]&&(SERIES[id].short||SERIES[id].name))||String(id||'—').toUpperCase()}
function renderDrivers(){const el=$('dataManager'); if(!el)return; const list=buildDrivers(); const q=norm(window.__dbq||''); const filtered=q?list.filter(d=>norm(d.name+' '+d.country).includes(q)):list; const sel=window.__dbsel||filtered[0]?.k; window.__dbsel=sel; const d=list.find(x=>x.k===sel)||filtered[0];
 const rows=filtered.slice(0,120).map((x,i)=>`<button class="dbfix-row ${x.k===sel?'active':''}" data-driver-key="${esc(x.k)}"><span>${i+1}</span><b>${esc(x.name)}</b><span>${svgFlag(x.country)} ${esc(x.country||'—')}</span><span>${x.starts}</span><span>${x.ow}/${x.cw}</span><span>${x.op}/${x.cp}</span><span>${x.ppO}/${x.ppC}</span><span>${x.flO}/${x.flC}</span></button>`).join('');
 const detail=d?`<aside class="dbfix-detail"><div class="profile"><div class="initials">${esc(d.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase())}</div><div><h2>${esc(d.name)} ${svgFlag(d.country)}</h2><div class="muted">${esc(d.country||'Nationality unknown')}</div><div class="edit-line"><input id="dbfixCountry" placeholder="Nationality" value="${esc(d.country||'')}"><input id="dbfixDob" type="date" value="${esc(d.dob||'')}"><button id="dbfixSave">Save</button></div></div></div><div class="statgrid"><div><small>Starts</small><b>${d.starts}</b></div><div><small>Wins O/C</small><b>${d.ow}/${d.cw}</b></div><div><small>Podiums O/C</small><b>${d.op}/${d.cp}</b></div><div><small>PP O/C</small><b>${d.ppO}/${d.ppC}</b></div><div><small>FL O/C</small><b>${d.flO}/${d.flC}</b></div><div><small>Finish %</small><b>${d.starts?Math.round(d.finishes*100/d.starts):0}%</b></div></div><h3>By series</h3><div class="seriesgrid">${Object.entries(d.series).map(([sid,s])=>`<div><b>${esc(seriesName(sid))}</b><span>${s.starts} starts · W ${s.ow}/${s.cw} · P ${s.op}/${s.cp} · PP ${s.ppO}/${s.ppC} · FL ${s.flO}/${s.flC}</span></div>`).join('')}</div><h3>Race history</h3><div class="hist"><div class="hhead"><span>Date</span><span>Series</span><span>Race</span><span>Team</span><span>Car</span><span>Class</span><span>O</span><span>C</span></div>${d.hist.map(h=>`<div><span>${esc(h.race.date||'')}</span><span>${esc(seriesName(h.race.series))}</span><span>${esc(h.race.event||h.race.name||'')}</span><span>${esc(h.e.team||'')}</span><span>${esc(h.e.model||'')}</span><span>${esc(h.e.class||'')}</span><span>P${opos(h.e)||'—'}</span><span>C${cpos(h.e)||'—'}</span></div>`).join('')}</div></aside>`:'';
 el.innerHTML=`<div class="dbfix"><section class="dbfix-list"><div class="dbfix-top"><h3>Drivers</h3><span>${filtered.length} / ${list.length}</span></div><input id="dbfixSearch" placeholder="Search driver / country" value="${esc(window.__dbq||'')}"><div class="dbfix-head"><span>#</span><span>Name</span><span>Nationality</span><span>Starts</span><span>Wins</span><span>Pod</span><span>PP</span><span>FL</span></div>${rows}</section>${detail}</div>`;
 const input=$('dbfixSearch'); if(input){input.oninput=e=>{const p=e.target.selectionStart; window.__dbq=e.target.value; renderDrivers(); const n=$('dbfixSearch'); if(n){n.focus(); try{n.setSelectionRange(p,p)}catch{}}};}
 document.querySelectorAll('[data-driver-key]').forEach(b=>b.onclick=()=>{window.__dbsel=b.dataset.driverKey; renderDrivers();});
 const save=$('dbfixSave'); if(save) save.onclick=()=>{const countries=JSON.parse(localStorage.getItem('scc_driver_countries_v082')||'{}'); const dobs=JSON.parse(localStorage.getItem('scc_driver_dobs_v082')||'{}'); countries[d.k]=$('dbfixCountry').value.trim(); dobs[d.k]=$('dbfixDob').value; localStorage.setItem('scc_driver_countries_v082',JSON.stringify(countries)); localStorage.setItem('scc_driver_dobs_v082',JSON.stringify(dobs)); renderDrivers();};}
function buildSimple(kind){const m=new Map(); allRaces().forEach(r=>{if(kind==='circuits'){const k=norm(r.circuit||r.event); if(!m.has(k))m.set(k,{name:r.circuit||r.event,country:r.country||'',races:new Set(),series:new Set()}); const x=m.get(k); x.races.add(r.id); x.series.add(r.series); return;} (r.entries||[]).forEach(e=>{const name=kind==='teams'?e.team:e.constructor; const k=norm(name||'Unknown'); if(!m.has(k))m.set(k,{name:name||'Unknown',races:new Set(),entries:0,series:new Set(),models:new Set()}); const x=m.get(k); x.races.add(r.id); x.entries++; x.series.add(r.series); x.models.add(e.model||e.class||'');});}); return [...m.values()].sort((a,b)=>b.races.size-a.races.size||a.name.localeCompare(b.name));}
function renderCards(kind){const items=buildSimple(kind); $('dataManager').innerHTML=`<section class="data-manager-panel"><div class="data-subhead"><h3>${kind==='teams'?'Teams':kind==='constructors'?'Constructors':'Circuits'}</h3><span>${items.length}</span></div><div class="data-grid">${items.map(x=>`<div class="data-card"><strong>${kind==='circuits'?svgFlag(x.country):''} ${esc(x.name)}</strong><span>${x.races.size} race${x.races.size===1?'':'s'}${kind==='circuits'?'':` · ${x.entries} entries`}</span><em>${[...x.series].map(seriesName).join(' · ')}</em><em>${[...x.models||[]].slice(0,6).join(', ')}</em></div>`).join('')}</div></section>`;}
window.showSccDatabase=function(tab){window.state=window.state||{}; window.state.dataTab=tab||'drivers'; document.querySelectorAll('.tab-content').forEach(s=>s.classList.remove('active')); const sec=$('tab-data'); if(sec)sec.classList.add('active'); document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='data')); document.querySelectorAll('[data-db-tab],[data-data-tab]').forEach(b=>b.classList.toggle('active',(b.dataset.dbTab||b.dataset.dataTab)===window.state.dataTab)); if(window.state.dataTab==='drivers')renderDrivers(); else renderCards(window.state.dataTab);};
// disabled old DB click listener; v0.8.4 owns DB routing
function addCss(){const css=`.dbfix{display:grid;grid-template-columns:minmax(720px,1fr) minmax(560px,44vw);gap:16px}.dbfix-list,.dbfix-detail{background:rgba(9,18,31,.86);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:14px}.dbfix-top{display:flex;justify-content:space-between;align-items:center}.dbfix input{background:#081422;border:1px solid #263a53;color:#eaf2ff;border-radius:9px;padding:8px}.dbfix-head,.dbfix-row{display:grid;grid-template-columns:38px 1.4fr 1.1fr 70px 70px 70px 70px 70px;gap:10px;align-items:center;padding:8px;border-bottom:1px solid rgba(255,255,255,.06)}.dbfix-head{color:#9fb0c7;text-transform:uppercase;font-weight:800;font-size:12px}.dbfix-row{width:100%;background:transparent;color:inherit;border-left:0;border-right:0;border-top:0;text-align:left;cursor:pointer}.dbfix-row:hover,.dbfix-row.active{background:rgba(30,144,255,.12)}.profile{display:flex;gap:14px;align-items:center}.initials{width:70px;height:70px;border-radius:16px;background:#123456;display:grid;place-items:center;font-size:28px;font-weight:900}.edit-line{display:flex;gap:8px;margin-top:8px}.edit-line button{background:#d7233f;color:white;border:0;border-radius:8px;padding:8px 12px}.statgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.statgrid div,.seriesgrid div{background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px}.statgrid small,.seriesgrid span{display:block;color:#9fb0c7}.statgrid b{font-size:22px}.seriesgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.hist{overflow:auto}.hist .hhead,.hist>div{display:grid;grid-template-columns:90px 80px 1.4fr 1.1fr 1fr 80px 50px 50px;gap:8px;padding:7px;border-bottom:1px solid rgba(255,255,255,.06)}.hist .hhead{font-weight:800;color:#9fb0c7;text-transform:uppercase}.flag-inline svg,.flag-mini svg{width:22px;height:14px;vertical-align:-2px}`; const st=document.createElement('style'); st.textContent=css; document.head.appendChild(st);}

// WEC parser override: stable classification rows and starting-grid poles.
const MODELS=['BMW M Hybrid V8','Ferrari 499P','Aston Martin Valkyrie','Toyota TR010 Hybrid','Toyota GR010 Hybrid','Peugeot 9X8','Genesis GMR-001-Hypercar','Genesis GMR-001','Cadillac V-Series.R','Alpine A424','McLaren 720S LMGT3 Evo','Aston Martin Vantage AMR LMGT3','Porsche 911 GT3 R','Ferrari 296 LMGT3 Evo','Lexus RC F LMGT3','Corvette Z06 LMGT3.R','Mercedes-AMG LMGT3','BMW M4 LMGT3 Evo','Ford Mustang LMGT3'];
function consFromModel(m){m=clean(m); if(/BMW/i.test(m))return'BMW'; if(/Ferrari/i.test(m))return'Ferrari'; if(/Aston/i.test(m))return'Aston Martin'; if(/Toyota/i.test(m))return'Toyota'; if(/Peugeot/i.test(m))return'Peugeot'; if(/Genesis/i.test(m))return'Genesis'; if(/Cadillac/i.test(m))return'Cadillac'; if(/Alpine/i.test(m))return'Alpine'; if(/McLaren/i.test(m))return'McLaren'; if(/Porsche/i.test(m))return'Porsche'; if(/Lexus/i.test(m))return'Lexus'; if(/Corvette/i.test(m))return'Corvette'; if(/Mercedes/i.test(m))return'Mercedes-AMG'; if(/Ford/i.test(m))return'Ford'; return m.split(' ')[0]||'';}
function findModel(s){const low=s.toLowerCase(); return MODELS.find(m=>low.includes(m.toLowerCase()))||'';}
function splitDrivers(s){return clean(s).split(/\s*\/\s*/).map(titleName).filter(Boolean).filter(x=>x.length>2);}
function driverPart(s){const m=s.match(/([A-ZÁÉÍÓÚÄËÏÖÜÑÇØ][.A-ZÁÉÍÓÚÄËÏÖÜÑÇØ'\- ]{2,}\s*\/\s*[A-ZÁÉÍÓÚÄËÏÖÜÑÇØ][.A-ZÁÉÍÓÚÄËÏÖÜÑÇØ'\- ].*)$/u); return m?m[1]:'';}
function parseOneWecLine(line,pos,no,status){let l=clean(line); const total=(l.match(/\d{1,2}:\d{2}:\d{2}\.\d{3}/)||[])[0]; if(!total)return null; const cls=/LMGT3/i.test(l)?'LMGT3':'HYP'; const best=[...l.matchAll(/\b\d{1,2}:\d{2}\.\d{3}\b/g)].map(m=>m[0]).pop()||''; const model=findModel(l); const constructor=consFromModel(model||l); let before=l.split(total)[0]; let after=l.split(total).slice(1).join(' '); before=before.replace(new RegExp('^'+pos+'\\s+'+no+'\\s+'),''); before=before.replace(/\s+(HYPERCAR|LMGT3)\s+[A-Z]\s+\d+\s*$/i,''); const lapsMatch=l.slice(0,l.indexOf(total)).match(/\b(\d{2,3})\s*$/); const laps=lapsMatch?+lapsMatch[1]:0; let team=before, drivers=''; if(model){const ix=before.toLowerCase().indexOf(model.toLowerCase()); const pre=before.slice(0,ix).trim(); const dp=driverPart(pre); if(dp){drivers=dp; team=pre.slice(0,pre.length-dp.length).trim();} else team=pre;}
 if(!drivers){const dp=driverPart(after); if(dp)drivers=dp;} const dlist=splitDrivers(drivers); const nums=after.replace(best,'').match(/(?:\d+\s+Laps?|\d+\s+Lap|\d+\.\d{3})/gi)||[]; let gap='—', int=''; if(status==='FIN'&&pos>1){gap=nums[0]||'—'; int=nums[1]||'';} if(status!=='FIN')gap=status; return {__sccParsed:true,pos,no,class:cls,team:team||constructor,constructor,model:model||constructor,laps,time:total,total_time:total,gap,int,status,bestLap:best,drivers:dlist.map(n=>[n,countryFor(n)]),bestLapNo:''};}
function parseWecClassText(text){const body=(window.pdfTextBody?pdfTextBody(text):String(text||'')).replace(/\r/g,''); if(!/Final\s+Classification/i.test(body)||!/FIA\s*WEC|World\s+Endurance/i.test(body))return []; const lines=body.split('\n').map(clean).filter(Boolean); const out=[]; let status='FIN'; let ncpos=900; for(const line of lines){ if(/^Not\s+classified/i.test(line)){status='NC'; continue;} if(/^Retired/i.test(line)){status='RET'; continue;} if(/^Circuit\s+Best|^Circuit\s+Race|^CAR\s+|^Published|^Stewards|^Timekeeper/i.test(line))break; if(!/(HYPERCAR|LMGT3)/i.test(line))continue; let m=line.match(/^(\d{1,2})\s+(0?\d{1,3})\s+(.+)/); if(m){const r=parseOneWecLine(line,+m[1],m[2],status); if(r)out.push(r); continue;} m=line.match(/^(0?\d{1,3})\s+(.+)/); if(m&&status!=='FIN'){const r=parseOneWecLine(`${ncpos++} ${line}`,ncpos-1,m[1],status); if(r)out.push(r);}}
 const by=new Map(); out.forEach(r=>{const k=r.no+'|'+r.status; if(!by.has(k))by.set(k,r)}); return [...by.values()].sort((a,b)=>(a.status==='FIN'?0:a.status==='NC'?1:2)-(b.status==='FIN'?0:b.status==='NC'?1:2)||(+a.pos||999)-(+b.pos||999));}
function parseWecGrid(text){const body=(window.pdfTextBody?pdfTextBody(text):String(text||'')); if(!/Final\s+Starting\s+Grid/i.test(body))return []; const lines=body.split('\n').map(clean).filter(Boolean); const items=[]; for(const line of lines){ if(!/\d:\d{2}\.\d{3}/.test(line))continue; const times=[...line.matchAll(/\d:\d{2}\.\d{3}/g)].map(m=>m[0]); const nums=[...line.matchAll(/\b(0?\d{1,3})\b/g)].map(m=>m[1]).filter(n=>+n>0||/^0/.test(n)); if(nums.length>=4&&times.length>=2){items.push({no:nums[nums.length-4],grid:+nums[nums.length-3],time:times[times.length-1]}); items.push({no:nums[nums.length-1],grid:+nums[nums.length-2],time:times[times.length-2]});} else if(nums.length>=2&&times.length){items.push({no:nums[nums.length-2],grid:+nums[nums.length-1],time:times[times.length-1]});}}
 const entries=(window.state&&state.race&&state.race.entries)||[]; const getE=no=>entries.find(e=>String(e.no)===String(no))||{}; const all=items.filter(x=>x.no&&x.grid).map(x=>{const e=getE(x.no); return {type:'PP',class:e.class||(+x.grid<=17?'HYP':'LMGT3'),no:x.no,driver:(e.drivers&&e.drivers[0]&&(Array.isArray(e.drivers[0])?e.drivers[0][0]:e.drivers[0]))||'',time:x.time,grid:x.grid,constructor:e.constructor,model:e.model,team:e.team};}); const out=[]; const overall=all.slice().sort((a,b)=>a.grid-b.grid)[0]; if(overall)out.push({...overall,class:'Overall'}); [...new Set(all.map(x=>x.class))].forEach(cls=>{const p=all.filter(x=>x.class===cls).sort((a,b)=>a.grid-b.grid)[0]; if(p)out.push({...p,class:cls});}); return out;}
const oldRows=window.rowsFromPdfText; window.rowsFromPdfText=function(type,text){const body=(window.pdfTextBody?pdfTextBody(text):String(text||'')); if(/Final\s+Classification/i.test(body)&&/FIA\s*WEC|World\s+Endurance/i.test(body)){const rows=parseWecClassText(text); if(type==='performance'||type==='fastest')return rows.filter(r=>r.bestLap).reduce((acc,r)=>{const sec=(window.parseTime?parseTime('0:'+r.bestLap):9999); const base={type:'FL',class:r.class,no:r.no,driver:(r.drivers[0]||[])[0]||'',lap:r.bestLapNo,time:r.bestLap,constructor:r.constructor,model:r.model,team:r.team,_sec:sec}; if(!acc.by[r.class]||sec<acc.by[r.class]._sec)acc.by[r.class]=base; if(!acc.by.Overall||sec<acc.by.Overall._sec)acc.by.Overall={...base,class:'Overall'}; return acc;},{by:{}}).by ? Object.values(rows.filter(r=>r.bestLap).reduce((acc,r)=>{const sec=(window.parseTime?parseTime('0:'+r.bestLap):9999); const base={type:'FL',class:r.class,no:r.no,driver:(r.drivers[0]||[])[0]||'',lap:r.bestLapNo,time:r.bestLap,constructor:r.constructor,model:r.model,team:r.team,_sec:sec}; if(!acc[r.class]||sec<acc[r.class]._sec)acc[r.class]=base; if(!acc.Overall||sec<acc.Overall._sec)acc.Overall={...base,class:'Overall'}; return acc;},{})).map(({_sec,...x})=>x) : []; return rows;} if(/Final\s+Starting\s+Grid/i.test(body)&&/FIA\s*WEC|World\s+Endurance/i.test(body)) return parseWecGrid(text); return oldRows?oldRows(type,text):[];};
function boot(){addCss(); document.title='SCC v0.8.2.1 · DB/import hotfix'; document.querySelectorAll('.brand span').forEach(x=>x.textContent='v0.8.2.1'); if(window.state&&state.dataTab) setTimeout(()=>window.showSccDatabase(state.dataTab),50);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot); else boot();
})();
